server:
  port: 8082

spring:
  application:
    name: Server-Provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://wrj:wrj@peer1:8080/eureka/,http://wrj:wrj@peer2:8081/eureka/