server:
  port: 8081

spring:
  application:
    name: Eureka-Server
  security:
    user:
      name: wrj
      password: wrj

eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://wrj:wrj@peer1:8080/eureka/
  server:
    enable-self-preservation: false