server:
  port: 9000

spring:
  application:
    name: Server-Consumer
  cloud:
    loadbalancer:
      retry:
        #开启重试机制，即获取服务失败是否从另外一个节点重试，默认false
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://wrj:wrj@peer1:8080/eureka/,http://wrj:wrj@peer2:8081/eureka/